---
plugin: gcp_compute
instance_name: 
  - centos
  - ubuntu
  - mysql
machine_type: g1-small
disk_size_gb: 50
ip_cidr_range: 172.16.0.0/28
regions:
  - australia-southeast1
zones:
  - australia-southeast1-b
auth_kind: serviceaccount
scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: /etc/ansible/workspace/GCP_provisioning/account.json
projects:
  - gcp-cm-tool
